version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: eduthrift-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: eduthrift
      MYSQL_USER: antons
      MYSQL_PASSWORD: "@Nt0n101!"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-admin.sql:/docker-entrypoint-initdb.d/init-qa.sql  # ADD THIS LINE

    networks:
      - eduthrift-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass123"]
      interval: 10s
      timeout: 20s
      retries: 10

  backend:
    image: ghcr.io/antonswarts15/eduthrift-backend:latest
    container_name: eduthrift-backend
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/eduthrift
      - SPRING_DATASOURCE_USERNAME=antons
      - SPRING_DATASOURCE_PASSWORD=@Nt0n101!
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - eduthrift-net

  frontend:
    image: ghcr.io/antonswarts15/eduthrift-frontend:latest
    container_name: eduthrift-frontend
    ports:
      - "3000:80"
    restart: always
    networks:
      - eduthrift-net

  admin:
    image: ghcr.io/antonswarts15/eduthrift-admin:latest
    container_name: eduthrift-admin
    ports:
      - "3001:80"
    restart: always
    networks:
      - eduthrift-net

volumes:
  mysql_data:

networks:
  eduthrift-net:
    driver: bridge