# ---- Build stage ----
FROM node:18-alpine AS build
WORKDIR /app

# Build-time API URL
ARG REACT_APP_API_URL=http://154.65.107.50:8080
ENV REACT_APP_API_URL=$REACT_APP_API_URL

COPY package*.json ./
RUN npm install

COPY . .

# This is where React reads REACT_APP_API_URL
RUN npm run build


# ---- Nginx stage ----
FROM nginx:alpine
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
