name: Build Backend Image

on:
  push:
    branches: [ "main" ]
    paths:
      - "backEnd/**"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker build -t ghcr.io/antonswarts15/eduthrift-backend:latest ./backEnd
          docker push ghcr.io/antonswarts15/eduthrift-backend:latest
